name: PortfolioPulse CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install and check Next.js app
      - name: Install App Deps
        run: npm install
      - name: Typecheck App
        run: npx tsc

      # Install and check AWS Infra
      - name: Install Infra Deps
        run: |
          cd infra
          npm install
      - name: Typecheck Infra
        run: |
          cd infra
          npx tsc