name: PortfolioPulse CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # NEXT.JS APP CHECK
      - name: Install App Deps
        run: npm install
      
      # We run 'next build' instead of 'npx tsc' 
      # Next.js will automatically run a strict type-check during the build
      - name: Build and Typecheck App
        run: npm run build

      # AWS INFRA CHECK
      - name: Install Infra Deps
        run: |
          cd infra
          npm install
      - name: Typecheck Infra
        run: |
          cd infra
          npx tsc